public class Hehe {
    String name;
    boolean stupid;
    boolean wearingBlueShirt;

    public static void main(String[] args) {
        while (wearingBlueShirt) {
            if (name == "Tyler") {
                stupid = true;
            } else {
                stupid = false;
            }
        }
    }

    public static Hehe(String name, boolean wearingBlueShirt = true) {
        name = name;
        wearingBlueShirt = wearingBlueShirt;
        while (wearingBlueShirt) {
            if (name == "Tyler") {
                stupid = true;
            } else {
                stupid = false;
            }
        }
    }

}